---
- name: Install dependencies
  yum:
    name: rrdtool
    state: present
  tags:
    - rstudio-server

- name: Install R Studio Server
  yum:
    name: http://download2.rstudio.org/rstudio-server-rhel-0.99.473-x86_64.rpm
    state: present
  when: not custom_repo
  tags:
    - rstudio-server

- name: Install R Studio Server
  yum:
    name: rstudio-server
    state: latest
    disable_gpg_check: yes
  when: custom_repo
  tags:
    - rstudio-server
