- name: Activate Julia repo
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/nalimilan/julia/repo/epel-6/nalimilan-julia-epel-6.repo
    dest: /etc/yum.repos.d/nalimilan-julia-epel-6.repo
  when: not 'production' in group_names

- name: Install dependency
  yum:
    name: utf8proc-devel
    state: present

- name: Create needed symlink
  file:
    path: /usr/lib64/libutf8proc.so.0.1
    src: /usr/lib64/libutf8proc.so.1.3.0
    state: link
    mode: 0755

- name: Install Julia
  yum:
    name: julia
    state: present
    disable_gpg_check: yes
